services:

  server:
    image: node:slim
    restart: always
    container_name: server
    ports: 
      - 5000:5000
    volumes:
      - ./server:/server
      - ./package.json:/package.json:ro
    command: "npm run server"
